### ISSUE TITLE
General Maintenance 

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/ghostwriter#7]
The plugins seems to work ok (double check if you can) but it needs a little maintenance.

- Removing legacy Github updater code
- Updating package.json to remove vulnerable dependencies
- Add blocks.json following the instructions here (https://github.com/WordPress/wporg-plugin-guidelines/blob/block-guidelines/blocks.md#4-block-plugins-must-include-a-blockjson-file)

**Comment by jrtashjian** [comment]
All updates have been made except the block.json file. Since we didn't build this as a block and instead as a style, we don't use a block.json file.

We can create a block for this though that is identical to a heading block and can be transformed to and from the core heading block.
