### ISSUE TITLE
Rename the plugin

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/ghostwriter#8]
We need to rename this as there is already a plugin in the repo with this name. 

Let's go with ghstwrtr (I'm going to be lazy and just remove the vowels). We only need to rename the actual plugin name. The style and everything else can change the same. I think we just need to change what's in readme.txt but I thought I'd have to do it so I don't screw anything up.

**Comment by jrtashjian** [comment]
I've actually already renamed the plugin to avoid this conflict. A common practice is to prefix the name which I've done here: `sbb-ghostwriter`

`sbb` is the prefix which stands for 'sortabrilliant blocks'. Would you like a different prefix? We can apply this to all the plugins.

**Comment by nickhamze** [comment]
When I install the plugin on my test site and I click on the more info button it brings up this's plugin information:
https://wordpress.org/plugins/ghostwriter/

I assumed that is because they have the same name.

**Comment by nickhamze** [comment]
<img width="1113" alt="Screen Shot 2020-01-19 at 3 11 41 PM" src="https://user-images.githubusercontent.com/158918/72688573-19475280-3ace-11ea-9a5c-aa9bd85785c0.png">

**Comment by jrtashjian** [comment]
This is most likely because the plugin folder on your website is named `ghostwriter`. Delete the plugin entirely and re-upload the new one. That should fix it. The "View Details" link will no longer show until `sbb-ghostwriter` exists in the directory.

**Comment by nickhamze** [comment]
ah, it goes by folder name. Sorry.
